# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npP4jbrewlTZhk_LFbFL_96jh04OrPHJ
"""

my_set={1,2,3,4,5,6}
my_set.add(7)
my_set.remove(3)
my_set.discard(2)
my_set.add(10)
print('updated set:',my_set)

my_list=[1, 2, 3, 4, 5, 6]
my_list.append(7)
my_list.remove(5)
my_list[0]
print(my_list)

my_dict={'name':'harsh','age':'19', 'city': 'banglore'}
my_dict['gender']='male'
del my_dict['age']
my_dict['city']='Goa'
print('updated dictionary:',my_dict)

